<?php
/**
 * Copyright (c) 2010 WPProsperent.com
 *
 * This file is part of WP Prosperent Plugin
 */
?>
<a href="<?php esc_attr_e($this->pluginHref) ?>"
	title="<?php esc_attr_e($this->pluginText) ?>"><?php esc_html_e($this->pluginText) ?></a>
| Version <?php esc_html_e($this->pluginVersion) ?> | By
<a href="<?php esc_attr_e($this->authorHref) ?>"
	title="<?php esc_attr_e($this->authorText) ?>"><?php echo esc_html_e($this->authorText) ?></a>
<br />
